ktor {
    deployment {
        port = 8090
        port = ${?PORT}
    }
    application {
        modules = [ com.portfolio.ai.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/ai_service"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "PLACEHOLDER_POSTGRES_PASSWORD"
    password = ${?DATABASE_PASSWORD}
}
